version: "3.8"

services:
  service-mysql:
    image: mysql:8.0.26
    container_name: database-mysql
    restart: no
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    ports:
    - 3307:3306
    - 33061:33060
    networks:
    - net-app-distri

networks:
  net-app-distri:
    name: netappdistri